# Generated by Django 4.2.3 on 2024-12-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_rename_name_subject_subject_delete_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
