# Generated by Django 4.2.3 on 2024-12-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='std',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(unique=True),
        ),
    ]
