# Generated by Django 4.2.3 on 2024-12-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_remove_student_std_alter_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$sYsxWrKN3YCoxKn3El42Pu$pXDB40LuIw9+VMdMD4sYaEnKVy4+Tn4qDL4ikp3H/Wg=', max_length=128),
        ),
    ]
