# Generated by Django 4.2.3 on 2024-12-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$oiWwEKvXJkw15qZDIvTqgK$nqKRXfj+Be/ZiGgjlUb4WddAveAbTc39Lozaaj0Iy44=', max_length=128),
        ),
    ]
