# Generated by Django 4.2.3 on 2024-12-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='default', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$8usomjP1kz0sK7ZLtlqRrl$4dCSuXIZczoY9WOSOCApbXVjFQ9OceJovOQztGaCy7o=', max_length=128),
        ),
    ]
